### ISSUE TITLE
Solution not buildable in porting-assistant 1.9.0 (but in Visual Studio 2022 and msbuild from cmd line it is buildable)

### ISSUE THREAD

**Issue by WiseSewaTroll** [aws/porting-assistant-dotnet-client#1568]
Hi,

A solution that is buildable in VisualStudio 2022 can not be build in the porting-assistant when choosing assess a new solution.

From View Log:
`[2022-11-09 11:28:25 DBG] (1.9.0) PortingAssistant.Client.Analysis.PortingAssistantAnalysisHandler: [24] Building project : C:\WEBSERVICES\TestWcfServices\TestWcfServices.csproj
[2022-11-09 11:28:26 ERR] (1.9.0) PortingAssistant.Client.Analysis.PortingAssistantAnalysisHandler: Build error: Codelyzer wasn't able to retrieve the MSBuild path
System.NullReferenceException: Object reference not set to an instance of an object.
   at Codelyzer.Analysis.Common.MSBuildDetector.<>c__DisplayClass12_0.<GetMsBuildPathFromVSDirectory>b__5(FileInfo msbuild)
   at System.Linq.Enumerable.WhereListIterator`1.ToList()
   at Codelyzer.Analysis.Common.MSBuildDetector.GetMsBuildPathFromVSDirectory(DirectoryInfo vsDirectory, List`1 editions, String[] targets, String projectToolsVersion)
   at Codelyzer.Analysis.Common.MSBuildDetector.GetFileSystemMsBuildExePath(String programFilesPath, String programFilesX86Path, String toolsVersion)
   at Codelyzer.Analysis.Common.MSBuildDetector.GetFirstMatchingMsBuildFromPath(String programFilesPath, String programFilesX86Path, String toolsVersion)
   at Codelyzer.Analysis.Build.WorkspaceBuilderHelper.GetEnvironmentOptions(Boolean requiresNetFramework, String toolsVersion)
   at Codelyzer.Analysis.Common.MSBuildDetector.GetMsBuildPathFromVSDirectory(DirectoryInfo vsDirectory, List`1 editions, String[] targets, String projectToolsVersion)
   at Codelyzer.Analysis.Common.MSBuildDetector.GetFileSystemMsBuildExePath(String programFilesPath, String programFilesX86Path, String toolsVersion)
   at Codelyzer.Analysis.Common.MSBuildDetector.GetFirstMatchingMsBuildFromPath(String programFilesPath, String programFilesX86Path, String toolsVersion)
   at Codelyzer.Analysis.Build.WorkspaceBuilderHelper.GetEnvironmentOptions(Boolean requiresNetFramework, String toolsVersion)`

### Screenshots
![image](https://user-images.githubusercontent.com/24988423/200837476-9a01cf51-e339-4038-80b3-1cc9d6ccd51e.png)

### Desktop (please complete the following information)
 - OS: Windows 10 pro

**Comment by WiseSewaTroll** [comment]
And some relevant environment vars:
![image](https://user-images.githubusercontent.com/24988423/200815620-cdadfda0-7e5f-4cf9-8bb9-bdcb235e6020.png)

**Comment by WiseSewaTroll** [comment]
Some stack belonging to the exception:
`
[12:26:41 INF] Loading the Workspace (Solution): C:\Test\test.sln
[12:26:41 INF] Loading the Solution Done: C:\Test\test.sln
[12:26:41 DBG] Building the project : C:\Test\TestWcfServices.csproj
[12:26:42 ERR] Build error: Codelyzer wasn't able to retrieve the MSBuild path
System.NullReferenceException: Object reference not set to an instance of an object.
   at Codelyzer.Analysis.Common.MSBuildDetector.<>c__DisplayClass12_0.<GetMsBuildPathFromVSDirectory>b__5(FileInfo msbuild)
   at System.Linq.Enumerable.WhereListIterator`1.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Codelyzer.Analysis.Common.MSBuildDetector.GetMsBuildPathFromVSDirectory(DirectoryInfo vsDirectory, List`1 editions, String[] targets, String projectToolsVersion)
   at Codelyzer.Analysis.Common.MSBuildDetector.GetFileSystemMsBuildExePath(String programFilesPath, String programFilesX86Path, String toolsVersion)
   at Codelyzer.Analysis.Build.WorkspaceBuilderHelper.GetEnvironmentOptions(Boolean requiresNetFramework, String toolsVersion)
[12:26:42 DBG] Exception : C:\Test\TestWcfServices.csproj
[12:26:42 DBG]    at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Buildalyzer.Environment.ProcessRunner.Start()
   at Buildalyzer.ProjectAnalyzer.BuildTargets(BuildEnvironment buildEnvironment, String targetFramework, String[] targetsToBuild, AnalyzerResults results)
   at Buildalyzer.ProjectAnalyzer.Build(String targetFramework, BuildEnvironment buildEnvironment)
   at Buildalyzer.ProjectAnalyzer.Build(String targetFramework, EnvironmentOptions environmentOptions)
   at Buildalyzer.ProjectAnalyzer.Build(EnvironmentOptions environmentOptions)
   at Codelyzer.Analysis.Build.WorkspaceBuilderHelper.BuildProject(IProjectAnalyzer projectAnalyzer)
`

**Comment by WiseSewaTroll** [comment]
Also happens when using the porting-assistant-client as a nuget package

![image](https://user-images.githubusercontent.com/24988423/200843972-33fa0b4a-e205-4e91-91e6-7b256db543f1.png)

**Comment by WiseSewaTroll** [comment]
Fixed by reinstalling VS 2022
