### ISSUE TITLE
ArgumentNullException thrown in ApplyPortingChanges

### ISSUE THREAD

**Issue by ShanshanHe** [aws/porting-assistant-dotnet-client#305]
## Describe the bug
```
PortingAssistant.Client.Model.PortingAssistantException: Could not apply porting changes
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at PortingAssistant.Client.Client.PortingAssistantClient.<>c.<ApplyPortingChanges>b__7_1(RecommendedAction recommendation)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at PortingAssistant.Client.Client.PortingAssistantClient.ApplyPortingChanges(PortingRequest request)
   --- End of inner exception stack trace ---
   at PortingAssistant.Client.Client.PortingAssistantClient.ApplyPortingChanges(PortingRequest request)
```

### Expected behavior
No exception should be thrown.

### Steps to Reproduce
Following the README's recommended code changes to use PortingAssistant.Client.Client.

### Desktop (please complete the following information)
 - OS: [e.g. Windows, macOS, Linux, etc]
 - Version/Distro: [e.g. 11, Big Sur, Ubuntu 18.04]

**Comment by ShanshanHe** [comment]
Fixed in [this PR](https://github.com/aws/porting-assistant-dotnet-client/pull/306)
